[package]
name = "myrustlib"
version = "0.1.0"
authors = ["iotanbo <yurizappo@gmail.com>"]
edition = "2018"

[lib]
name = "myrustlib"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

