[package]
name = "p1_fluent_templates"
version = "0.1.0"
authors = ["iotanbo <yurizappo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent-templates = "0.6"
unic-langid = "0.9"
# phf = "0.8.0"
